name: Mekusshop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with: 
       node-version: 20

    - name: install dependencies
      run: npm ci

    - name: log into dockerhub
      uses: docker/login-actions@v2
      with:

       username: ${{ secret.DOCKERHUB_USERNAME }}
       password: ${{ secret.DOCKERHUB_TOKEN }}

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mekusshop-node:latest

    - name: push Docker image to dockerhub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mekusshop-node:latest .
